### ISSUE TITLE
Typing Backwards

### ISSUE THREAD

**Issue by SynnGraffkin** [monster860/FastDMM2#7]
I am having an issue with FastDMM2 where typing in variable fields forces the input to the far left of the box. If I wanna type "-8" for a Pixel variable, I would need to do 8- so it goes in order and I don't need to reposition the cursor every time. Attached is an example of me just typing "D" in a camera name field.

![Example](https://user-images.githubusercontent.com/6519623/81028207-6ddcc680-8e4e-11ea-9643-4f7fe7a2365e.gif)

**Comment by monster860** [comment]
what browser are you using

**Comment by SynnGraffkin** [comment]
I use Firefox.

**Comment by martinlyra** [comment]
I use Firefox and I've the same issue as well. I was able to reproduce this issue on both Windows 10 and Linux.

**Comment by martinlyra** [comment]
The cause seems to be this line https://github.com/monster860/FastDMM2/blob/58dfa3044e75fad49f3edbf72b36a8e9ebe89a57/lib/panels/vars_panel.js#L218

The text content is updated every keystroke without maintaining the cursor. Most browsers automatically restore cursor position when this happens, but Firefox lacks that feature.

**Comment by SynnGraffkin** [comment]
This could also just be related to using Firefox, but with Select, I haven't been able to copy / paste either. I can select / drag / cut / delete visible and such, but haven't been able to Paste.

**Comment by martinlyra** [comment]
I had similar issue related to the Select feature on Firefox, but I think it's a different issue on its own.
